---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: grpcs-gateway
  namespace: aks-istio-ingress
spec:
  selector:
    istio: aks-istio-ingressgateway-internal  
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH
    hosts:
     - "api-v2.bjdcsa.cloud"
  - port:
      number: 443
      name: http2
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: grpc-ingress-tls
    hosts:
    - "api-v1.bjdcsa.cloud"
