
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hellogreeter-sa-identity
  namespace: hellogrpc
  annotations:
    azure.workload.identity/client-id: 71e83a92-8a66-44f4-bf3a-92d5b58f5506
    azure.workload.identity/tenant-id: 16b3c013-d300-468d-ac64-7eda0820b6d3
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: hello-service-cert
  namespace: hellogrpc
spec:
  provider: azure
  secretObjects:                               
  - secretName: hello-service-cert
    type: kubernetes.io/tls
    data: 
    - objectName: tls
      key: tls.key
    - objectName: tls
      key: tls.crt
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    keyvaultName: hawk-47407-kv
    clientID: 71e83a92-8a66-44f4-bf3a-92d5b58f5506
    cloudName: ""                                         
    objects:  |
      array:
        - |
          objectName: grpc-wildcard-certificate
          objectAlias: tls
          objectType: secret
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
    tenantId: 16b3c013-d300-468d-ac64-7eda0820b6d3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellogreeter-v2
  namespace: hellogrpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellogreeter
      version: v2      
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: hellogreeter
        version: v2
    spec:
      serviceAccountName: hellogreeter-sa-identity
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000  
        supplementalGroups: [2000]
        fsGroup: 2000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: hellogreeter
        image: bjd145/hello-service:06c93709b309
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false  
        env:
        - name: HELLO_GRPC_VERSION
          value: "v2"
        resources:
          limits:
            memory: "512Mi"
            cpu: "2"
          requests:
            memory: "64Mi"
            cpu: "0.25"
        volumeMounts:
        - mountPath: /app/certs
          name: tls-volume
      tolerations:
      - key: "reservedFor"
        operator: "Equal"
        value: "apps"
        effect: "NoSchedule"
      volumes:
      - name: tls-volume
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "hello-service-cert"
        #secret:
        #  secretName: hello-service-cert
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service-v2
  namespace: hellogrpc
spec:
  ports:
  - port: 5003
    targetPort: 5003
    protocol: TCP
  type: ClusterIP 
  selector:
    app: hellogreeter
    version: v2
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: hello-service-v2-vs
  namespace: hellogrpc
spec:
  hosts:
  - api-v2.bjdcsa.cloud
  gateways:
  - aks-istio-ingress/grpcs-gateway
  tls:
  - match:
    - port: 443
      sniHosts:
      - api-v2.bjdcsa.cloud
    route:
    - destination:
        host: hello-service-v2.hellogrpc.svc.cluster.local
        port:
          number: 5003