apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: grpc-tls
  namespace: aks-istio-ingress
spec:
  provider: azure
  secretObjects:                               
  - secretName: grpc-ingress-tls
    type: kubernetes.io/tls
    data: 
    - objectName: grpc-wildcard-certificate
      key: tls.key
    - objectName: grpc-wildcard-certificate
      key: tls.crt
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    keyvaultName: bunny-44189-kv
    clientID: 16ce9ff5-3609-4b1f-9626-577a6740251a
    cloudName: ""                                         
    objects:  |
      array:
        - |
          objectName: grpc-wildcard-certificate
          objectType: secret
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
    tenantId: 16b3c013-d300-468d-ac64-7eda0820b6d3